#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPm+ZOX+KvQwbs9dn/i+RrXT2x/B4642BpU9pZ+w99fT maksim@DESKTOP-U3S6BIN
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICsrrQZE2cs8uCZ4oUZcoErmtoLjiyY3nU3Hk0QlArQK maksim@DESKTOP-R5DV9UM
#package_update: true
runcmd:
# Install Zabbix Server and Agent2
  - wget https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu24.04_all.deb
  - dpkg -i zabbix-release_latest_7.0+ubuntu24.04_all.deb
  - apt update
  - apt install -y zabbix-agent2
  - sed -i 's/^Server=.*/Server=zabbix/' /etc/zabbix/zabbix_agent2.conf
  - sed -i 's/^ServerActive=.*/ServerActive=zabbix/' /etc/zabbix/zabbix_agent2.conf
  - echo "HostMetadata=linux" >> /etc/zabbix/zabbix_agent2.conf
  - systemctl restart zabbix-agent2
  - systemctl enable zabbix-agent2
# Install elasticsearch
  - apt install -y gnupg apt-transport-https
  - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
  - echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main" | tee /etc/apt/sources.list.d/elastic-7.x.list
  - apt update 
  - apt install -y elasticsearch
  - "sed -i 's/#network.host:.*/network.host: 0.0.0.0/' /etc/elasticsearch/elasticsearch.yml"
  - "sed -i 's/#http.port:.*/http.port: 9200/' /etc/elasticsearch/elasticsearch.yml"
  - "echo 'discovery.type: single-node' >> /etc/elasticsearch/elasticsearch.yml"
  - systemctl daemon-reload
  - systemctl enable elasticsearch.service
  - systemctl restart elasticsearch.service